remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: "mdsplit"
description: "A Tool to Split Bulky Markdown Files"

search_enabled: true

aux_links:
  "mdsplit on github":
    - "//github.com/alandefreitas/mdsplit"

aux_links_new_tab: false

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/mdsplit/tree/master/LICENSE.txt\">MIT license.</a>"
