//
// Created by Alan Freitas on 30/09/20.
//

#ifndef MDSPLIT_MDSPLITTER_H
#define MDSPLIT_MDSPLITTER_H

#include "mdsection.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <string>

namespace mdsplit {
    namespace fs = std::filesystem;

    class mdsplitter {
      public:
        mdsplitter() = default;

        /// Split the README.md and generate all files
        int run();

      public:
        /// Slugify a title string to a markdown anchor
        static std::string slugify(std::string_view);

      private:
        /// Go through the file, read all lines and put them
        /// in mdsection objects
        void find_sections();

        /// Identify a codeblock
        /// Most operations need to ignore codeblocks
        static bool is_codeblock(const std::string &str);

        /// Remove the automatic github actions autotoc
        /// because we are going to include a TOC for
        /// all files later
        void remove_auto_toc();

        /// Remove undesirable html tags
        /// For instance, jekyll does not handle details and summary well
        void remove_html_tags();

        /// Make links relative to the new directories
        void run_update_links();

        /// Create a table of contents at the end of each new file
        void create_subsection_links();

        /// Remove consecutive {{ (jekyll requirement) without messing with the
        /// original README.md
        void escape_jekyll();

        /// Reduce header levels in sections
        void reindent_headers();

        /// Add a front matter to all files
        void run_add_front_matter();

        /// Save all sections
        void save_sections();

        /// Find a relative path
        fs::path relative_path(const fs::path &path, const fs::path &base);

        /// Check if path is a subdirectory of the documentation
        bool is_subdirectory(const fs::path &path, const fs::path &base);

        /// Check if it is an external url
        static bool is_external(const std::string &url);

        /// List markdown files not generated by mdsplit and delete them
        /// if they contain a comment telling mdsplit it's ok to do so
        void list_doc_outsiders();

      public /* getters and setters */:
        [[nodiscard]] const fs::path &input() const;
        void input(const fs::path &input);
        [[nodiscard]] const fs::path &output_dir() const;
        void output_dir(const fs::path &output_dir);
        [[nodiscard]] const std::vector<std::string> &clear_html_tags() const;
        void clear_html_tags(const std::vector<std::string> &clear_html_tags);
        [[nodiscard]] const std::string &repository() const;
        void repository(const std::string &repository);
        [[nodiscard]] short max_split_level() const;
        void max_split_level(short max_split_level);
        [[nodiscard]] bool include_toc() const;
        void include_toc(bool include_toc);
        [[nodiscard]] bool jekyll_escape() const;
        void jekyll_escape(bool jekyll_escape);
        [[nodiscard]] bool indent_headers() const;
        void indent_headers(bool indent_headers);
        [[nodiscard]] bool add_front_matter() const;
        void add_front_matter(bool add_front_matter);
        [[nodiscard]] bool update_links() const;
        void update_links(bool update_links);
        [[nodiscard]] bool remove_autotoc() const;
        void remove_autotoc(bool remove_autotoc);
        [[nodiscard]] const fs::path &current_output_file() const;
        void current_output_file(const fs::path &current_output_file);
        [[nodiscard]] const std::vector<mdsection> &sections() const;
        void sections(const std::vector<mdsection> &sections);
        [[nodiscard]] bool trace() const;
        void trace(bool trace);
        [[nodiscard]] bool erase_old_mdsplit_files() const;
        void erase_old_mdsplit_files(bool erase_old_mdsplit_files);

      private /* options */:
        fs::path input_ = "README.md";
        fs::path output_dir_ = fs::current_path() / "docs";
        std::vector<std::string> clear_html_tags_{"details", "summary"};
        std::string repository_;
        short max_split_level_{4};
        bool include_toc_{true};
        bool jekyll_escape_{true};
        bool indent_headers_{true};
        bool add_front_matter_{true};
        bool update_links_{true};
        bool remove_autotoc_{true};
        bool trace_{true};
        bool erase_old_mdsplit_files_{true};

      private /* processing */:
        /// Path to which are are currently saving contents
        fs::path current_output_file_ = output_dir_ / "index.md";

        /// List of sections we are going to transform to files
        std::vector<mdsection> sections_;
        void move_parents_to_subdirectories();
        void generate_navigation_files();
    };
} // namespace mdsplit

#endif // MDSPLIT_MDSPLITTER_H
