name: Docs Generator

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/docs.yml'

jobs:
  generateDOC:
    name: Docs Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use this action workflow to update your README.md with the table of contents
      - uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_HEADER_LEVEL: 3
          FOLDING: true
      # Use this step to use the latest version of mdsplit
      # Comment this step if you want the latest release
      - name: Download and build mdsplit from source
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8  -DCMAKE_CXX_FLAGS="-O2" -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j 2 --config Release
          sudo cmake --install .
          cd ..
      # Uncomment these steps to use the latest release of mdsplit
      #      - name: Download mdsplit
      #        uses: carlosperate/download-file-action@v1.0.3
      #        id: download-mdsplit
      #        with:
      #          file-url: 'https://github.com/alandefreitas/mdsplit/releases/download/v0.1.0/Executable.Linux.zip'
      #          file-name: 'mdsplit.zip'
      #          location: '.'
      #      - name: Unzip mdsplit
      #        run: |
      #          unzip mdsplit.zip
      #          rm -f mdsplit.zip
      #          sudo chmod +x mdsplit
      #          ls
      # Run mdsplit to generate docs
      - name: Generate Docs
        run: |
          mdsplit -r alandefreitas/mdsplit
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs-material
      # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
      - name: Install Navigation Plugin
        run: pip install mkdocs-awesome-pages-plugin
      # Deploy the mkdocs to the gh-pages branch
      - name: Deploy mkdocs
        run: mkdocs gh-deploy --force