name: Docs Generator

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/docs.yml'

jobs:
  generateDOC:
    name: Docs Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # use this same workflow to update README.md with the table of contents
      - uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_HEADER_LEVEL: 3
          FOLDING: true
      # build mdsplit and use it, but external projects would just use curl to get the binary
      - name: Download and build mdsplit
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8  -DCMAKE_CXX_FLAGS="-O2" -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j 2 --config Release
          sudo cmake --install .
          cd ..
      # run mdsplit to generate docs
      - name: Generate Docs
        run: |
          mdsplit -r alandefreitas/mdsplit
      # fetch to make sure nothing happened in the meanwhile and commit
      - name: Commit Docs
        run: |
          git fetch
          git add docs
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update Docs" -a
        continue-on-error: true
      # push docs back to repository
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}