name: Docs Generator

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/docs.yml'


jobs:
  generateDOC:
    name: Docs Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and build mdsplit
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8  -DCMAKE_CXX_FLAGS="-O2" -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j 2 --config Release
          sudo cmake --install .
          cd ..
      - name: Generate Docs
        run: |
          mdsplit -r alandefreitas/mdsplit
      - name: Publish Docs
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs
          commit-msg: Update Docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
